### ISSUE TITLE
readme.md - Instructions to increase Lambda function run time

### ISSUE THREAD

**Issue by sergiozygmunt** [swamplynx/ffpass-lambda#1]
I have deployed this useful project within AWS Lambda but when I ran any command except status I got 502 errors - I fixed this by increasing the AWS Lambda timeout time to 35 seconds. 
It's my understanding that the program waits for the Ford API to hear from the vehicle before returning a 200 so increasing the timeout from 3 seconds is ideal to prevent 502 errors.

**Comment by swamplynx** [comment]
Good catch. I'll add that to the READ ME. I think I set mine to 60 seconds, but 35 should be enough.
